master:
  host: 10.99.1.151
  port: 3306
  user: root
  pwd: "123456"
  db: test
  charset: utf8
slaves:
- host: 127.0.0.1
  port: 3306
  user: root
  pwd: ""
  db: xesvip
  charset: utf8
- host: 127.0.0.1
  port: 3306
  user: root
  pwd: ""
  db: xesvip
  charset: utf8
